### PR TITLE
Dark Theme

### PR DESCRIPTION
**Pull request by petalser**
Implemented by adding separate .html files.
Added few classes, addLogos function refactored to accept boolean as third parameter and consuming it to give "cards" proper styling.
Theme switching made with simple button, but I recommend to replace it with svg to match "github corner" visual style.

### CODE REVIEW

**Comment by hugovk** [comment]
Thanks for the PR, but rather than duplicating all the files, let's do it with the `prefers-color-scheme` CSS media feature.

For example, see https://github.com/hugovk/top-pypi-packages/blob/main/index.html

We can define some base colours as variables in `:root {}`, and then in `@media (prefers-color-scheme: dark) {:root { ... } }` define overrides for dark mode. And then we refer to these variables instead.

Please could you update the PR to do this?

**Comment by petalser** [comment]
> Thanks for the PR, but rather than duplicating all the files, let's do it with the `prefers-color-scheme` CSS media feature.
> 
> For example, see https://github.com/hugovk/top-pypi-packages/blob/main/index.html
> 
> We can define some base colours as variables in `:root {}`, and then in `@media (prefers-color-scheme: dark) {:root { ... } }` define overrides for dark mode. And then we refer to these variables instead.
> 
> Please could you update the PR to do this?

Thanks for response. So, if I got you right, you want me to define some colours with css variables and apply that colours to entire page? Please, confirm.
I can do that but I have to mention that I'd rather give the user a choice.

**Comment by hugovk** [comment]
> So, if I got you right, you want me to define some colours with css variables and apply that colours to entire page? Please, confirm.

Yes please.

> I can do that but I have to mention that I'd rather give the user a choice.

Generally I agree, but I think it's fine to use the system default for this small site.

**Comment by petalser** [comment]
I apologize for messed commit history for this update.

**Comment by hugovk** [comment]
Don't worry about the commit history, it's not too important here and I can squash merge at the end :)

Thank you, this is looking better, but please can you undo the unrelated formatting changes? It makes it harder to see what's actually changed.

And could you check the GitHub Corner icon as well? We can have that toggle too, compare with:

* https://hugovk.github.io/python-steering-council/
* https://github.com/hugovk/python-steering-council

**Comment by petalser** [comment]
> can you undo the unrelated formatting changes?

Unfortunately I have no idea how to do that

**Comment by hugovk** [comment]
Edit the files with unrelated changes so they look like the original, and then commit and push.

**Comment by petalser** [comment]
> Edit the files with unrelated changes so they look like the original

The only way I know how to do that is manual editing. I'm not gonna do that.

**Comment by hugovk** [comment]
Nor am I ;)

Shall we close this then?

**Pull request closed without merging**
